export const WINDOWS_CONTROL_CURSOR_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><title>Zyra Control Cursor</title><style>
:root{--accent-primary:#3b82f6;--accent-secondary:#60a5fa;--accent-primary-rgb:59 130 246;--accent-secondary-rgb:96 165 250;color-scheme:dark}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:transparent;pointer-events:none}
.cursor{position:absolute;left:0;top:0;opacity:0;will-change:transform;transition-property:transform;transition-timing-function:cubic-bezier(.2,.7,.2,1)}
.cursor.show{opacity:1}.visual{position:absolute;left:0;top:0;transform-origin:4px 4px;transition:transform 100ms cubic-bezier(.2,.7,.2,1)}
.cursor.pressing .visual{transform:scale(.92)}.cursor.dragging .visual{transform:scale(1.03)}
.pointer{position:absolute;left:-4px;top:-4px;width:24px;height:24px;color:var(--accent-secondary);filter:drop-shadow(0 1px 2px rgb(0 0 0/.72)) drop-shadow(0 0 5px rgb(var(--accent-primary-rgb)/.38))}
@media (prefers-reduced-motion:reduce){.cursor,.visual{transition:none!important}}
</style></head><body><div id="cursor" class="cursor"><div class="visual"><svg class="pointer" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4.037 4.688a.495.495 0 0 1 .651-.651l16 6.5a.5.5 0 0 1-.063.947l-6.124 1.58a2 2 0 0 0-1.438 1.435l-1.579 6.126a.5.5 0 0 1-.947.063z"/></svg></div></div><script>
const root=document.documentElement;
const applyAppearance=(value)=>{if(value.accentPrimary)root.style.setProperty('--accent-primary',String(value.accentPrimary));if(value.accentSecondary)root.style.setProperty('--accent-secondary',String(value.accentSecondary));if(value.accentPrimaryRgb)root.style.setProperty('--accent-primary-rgb',String(value.accentPrimaryRgb));if(value.accentSecondaryRgb)root.style.setProperty('--accent-secondary-rgb',String(value.accentSecondaryRgb));if(typeof value.reduceMotion==='boolean')root.dataset.reduceMotion=value.reduceMotion?'true':'false'};
globalThis.updateZyraCursor=(value)=>{applyAppearance(value);const cursor=document.querySelector('#cursor');const requestedDuration=Number(value.durationMs);const duration=root.dataset.reduceMotion==='true'?0:Math.max(90,Math.min(320,Number.isFinite(requestedDuration)&&requestedDuration>0?requestedDuration:110));cursor.style.transitionDuration=duration+'ms';cursor.style.transform='translate3d('+Number(value.x)+'px,'+Number(value.y)+'px,0)';cursor.className='cursor show '+String(value.phase||'idle')};
globalThis.hideZyraCursor=()=>document.querySelector('#cursor').className='cursor';
</script></body></html>`

export const WINDOWS_CONTROL_SAFETY_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><title>Zyra Control Indicator</title><style>
:root{--accent-primary:#3b82f6;--accent-secondary:#60a5fa;--accent-primary-rgb:59 130 246;--accent-secondary-rgb:96 165 250;--theme-background:#0c121f;--theme-surface:#131c2c;--theme-text:#f0f4f8;--theme-text-secondary:#aab4c3;--theme-border:#2c394c;--font-ui:"Bricolage Grotesque","Hanken Grotesk","Segoe UI",system-ui,sans-serif;color-scheme:dark}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:transparent;pointer-events:none;font-family:var(--font-ui)}
.edge{position:absolute;inset:0;overflow:hidden;opacity:0;box-shadow:inset 0 0 30px rgb(var(--accent-primary-rgb)/.33),inset 0 0 86px rgb(var(--accent-primary-rgb)/.155),inset 0 0 138px rgb(var(--accent-primary-rgb)/.065)}
.wave{position:absolute;display:block;will-change:transform;opacity:.88}
.wave.top,.wave.bottom{left:-12%;width:124%;height:150px;background:radial-gradient(ellipse 24% 105% at 17% 0%,rgb(var(--accent-secondary-rgb)/.5),transparent 74%),radial-gradient(ellipse 31% 108% at 54% 0%,rgb(var(--accent-primary-rgb)/.37),transparent 72%),radial-gradient(ellipse 25% 100% at 88% 0%,rgb(var(--accent-secondary-rgb)/.45),transparent 72%)}
.wave.top{top:-57px;animation:wave-horizontal 9s ease-in-out infinite alternate}
.wave.bottom{bottom:-57px;transform:rotate(180deg);animation:wave-horizontal-reverse 11s ease-in-out infinite alternate}
.wave.left,.wave.right{top:-12%;height:124%;width:150px;background:radial-gradient(ellipse 105% 25% at 0% 16%,rgb(var(--accent-primary-rgb)/.44),transparent 74%),radial-gradient(ellipse 108% 31% at 0% 52%,rgb(var(--accent-secondary-rgb)/.35),transparent 72%),radial-gradient(ellipse 100% 25% at 0% 86%,rgb(var(--accent-primary-rgb)/.42),transparent 72%)}
.wave.left{left:-57px;animation:wave-vertical 10s ease-in-out infinite alternate}
.wave.right{right:-57px;transform:rotate(180deg);animation:wave-vertical-reverse 12s ease-in-out infinite alternate}
.indicator{position:absolute;left:50%;top:18px;transform:translateX(-50%);display:flex;align-items:center;justify-content:space-between;gap:24px;max-width:calc(100% - 40px);min-height:54px;padding:12px 19px;border:1px solid var(--theme-border);border-radius:12px;background:color-mix(in srgb,var(--theme-surface) 96%,transparent);color:var(--theme-text);opacity:0;box-shadow:0 16px 42px color-mix(in srgb,var(--theme-background) 42%,transparent);font-family:var(--font-ui);font-size:13px;font-weight:520;letter-spacing:-.01em;line-height:1;white-space:nowrap;backdrop-filter:blur(18px)}
:root[data-active="true"] .edge{animation:edge-enter 460ms cubic-bezier(.2,.7,.2,1) both}:root[data-active="true"] .indicator{animation:indicator-enter 340ms 55ms cubic-bezier(.16,1,.3,1) both}
.label{min-width:0;display:flex;align-items:baseline;gap:5px;color:var(--theme-text-secondary)}.label>span{flex:0 0 auto}.application{min-width:0;overflow:hidden;color:var(--theme-text);font-weight:650;text-overflow:ellipsis}
.stop{display:flex;align-items:center;gap:7px;flex:0 0 auto;color:var(--theme-text-secondary);font-size:11px;font-weight:500}
kbd{min-width:30px;height:26px;display:inline-flex;align-items:center;justify-content:center;padding:0 9px;border:1px solid color-mix(in srgb,var(--theme-text) 16%,transparent);border-bottom-color:color-mix(in srgb,var(--theme-text) 28%,transparent);border-radius:7px;background:color-mix(in srgb,var(--theme-text) 7%,var(--theme-surface));color:var(--theme-text);box-shadow:0 1px 1px color-mix(in srgb,var(--theme-background) 36%,transparent);font:600 10px/1 var(--font-ui)}
:root[data-theme-appearance="light"]{color-scheme:light}
:root[data-compact="true"] .indicator{top:14px;min-height:48px;gap:18px;padding:10px 15px;font-size:12px}:root[data-compact="true"] kbd{height:24px}
@keyframes edge-enter{from{opacity:0;filter:saturate(.78)}to{opacity:1;filter:saturate(1)}}
@keyframes indicator-enter{from{opacity:0;transform:translateX(-50%) translateY(-9px) scale(.98)}to{opacity:1;transform:translateX(-50%) translateY(0) scale(1)}}
@keyframes wave-horizontal{from{transform:translate3d(-3%,0,0) scaleX(.97)}to{transform:translate3d(3%,5px,0) scaleX(1.03)}}
@keyframes wave-horizontal-reverse{from{transform:rotate(180deg) translate3d(-2%,0,0) scaleX(.98)}to{transform:rotate(180deg) translate3d(3%,-4px,0) scaleX(1.04)}}
@keyframes wave-vertical{from{transform:translate3d(0,-3%,0) scaleY(.97)}to{transform:translate3d(5px,3%,0) scaleY(1.03)}}
@keyframes wave-vertical-reverse{from{transform:rotate(180deg) translate3d(0,-2%,0) scaleY(.98)}to{transform:rotate(180deg) translate3d(-4px,3%,0) scaleY(1.04)}}
@media(max-width:520px){.indicator{top:10px;max-width:calc(100% - 20px);min-height:46px;gap:12px;padding:10px 12px;font-size:12px}.stop>span{display:none}}
@media(prefers-reduced-motion:reduce){.edge,.indicator,.wave{animation:none!important}.edge,.indicator{opacity:1}}
:root[data-reduce-motion="true"] .edge,:root[data-reduce-motion="true"] .indicator,:root[data-reduce-motion="true"] .wave{animation:none!important}:root[data-reduce-motion="true"] .edge,:root[data-reduce-motion="true"] .indicator{opacity:1}
</style></head><body><div class="edge" aria-hidden="true"><i class="wave top"></i><i class="wave right"></i><i class="wave bottom"></i><i class="wave left"></i></div><div id="indicator" class="indicator" role="status" aria-live="polite" aria-label="Zyra is using this app"><span id="label" class="label"><span>Zyra is using</span><strong class="application">this app</strong></span><span class="stop"><kbd id="key">Esc</kbd><span>to stop</span></span></div><script>
const root=document.documentElement;
const applyAppearance=(value)=>{root.style.setProperty('--accent-primary',String(value.accentPrimary||'#3b82f6'));root.style.setProperty('--accent-secondary',String(value.accentSecondary||'#60a5fa'));root.style.setProperty('--accent-primary-rgb',String(value.accentPrimaryRgb||'59 130 246'));root.style.setProperty('--accent-secondary-rgb',String(value.accentSecondaryRgb||'96 165 250'));root.style.setProperty('--theme-background',String(value.themeBackground||'#0c121f'));root.style.setProperty('--theme-surface',String(value.themeSurface||'#131c2c'));root.style.setProperty('--theme-text',String(value.themeText||'#f0f4f8'));root.style.setProperty('--theme-text-secondary',String(value.themeTextSecondary||'#aab4c3'));root.style.setProperty('--theme-border',String(value.themeBorder||'#2c394c'));root.style.setProperty('--font-ui',String(value.uiFont||'"Bricolage Grotesque","Hanken Grotesk","Segoe UI",system-ui,sans-serif'));root.dataset.themeAppearance=value.themeAppearance==='light'?'light':'dark';root.dataset.reduceMotion=value.reduceMotion?'true':'false';root.dataset.compact=value.compact?'true':'false'};
globalThis.updateZyraSafety=(value,entering=false)=>{applyAppearance(value);const applicationName=String(value.application||'this app');const key=String(value.key||'Ctrl+Alt+Esc');document.querySelector('#indicator').setAttribute('aria-label','Zyra is using '+applicationName+'. Press '+key+' to stop.');const label=document.querySelector('#label');label.textContent='';const prefix=document.createElement('span');prefix.textContent='Zyra is using';const application=document.createElement('strong');application.className='application';application.textContent=applicationName;label.append(prefix,application);document.querySelector('#key').textContent=key;if(entering){root.dataset.active='false';void document.body.offsetWidth}root.dataset.active='true'};
window.addEventListener('load',()=>{setTimeout(()=>{const fonts=document.createElement('link');fonts.rel='stylesheet';fonts.href='https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;500;600;700&family=Hanken+Grotesk:wght@400;500;600;700&display=swap';document.head.append(fonts)},0)},{once:true});
</script></body></html>`
