import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createDesktopBuildMetadata, resolveDistributionIdentity, canManageGlobalTerminalCommand, previewAutoUpdateDisabledReason } from '../src/shared/distribution-identity'
import { desktopNamespaceId } from '../src/main/assistant/agent-server-namespace'

const stable = createDesktopBuildMetadata({})
const preview = createDesktopBuildMetadata({ ZYRA_BUILD_DISTRIBUTION: 'preview', ZYRA_BUILD_SOURCE_SHA: 'a'.repeat(40), ZYRA_BUILD_SOURCE_REPOSITORY: 'example/source', GITHUB_RUN_ID: '123' })
const prod = resolveDistributionIdentity(false, stable)
const test = resolveDistributionIdentity(false, preview)
assert.equal(prod.appName, 'Zyra')
assert.equal(prod.appUserModelId, 'app.zyra.desktop')
assert.equal(prod.isolated, false)
assert.equal(test.appName, 'Zyra Preview')
assert.equal(test.appUserModelId, 'app.zyra.desktop.preview')
assert.equal(test.isolated, true)
assert.notEqual(test.userDataDirectoryName, prod.userDataDirectoryName)
assert.notEqual(desktopNamespaceId(`/profiles/${test.userDataDirectoryName}`), desktopNamespaceId(`/profiles/${prod.userDataDirectoryName}`))
assert.equal(resolveDistributionIdentity(true, preview, 'Fixture A').appName, 'Zyra-dev-fixture-a')
assert.equal(canManageGlobalTerminalCommand(true, stable), true)
assert.equal(canManageGlobalTerminalCommand(false, stable), false)
assert.equal(canManageGlobalTerminalCommand(true, preview), false)
assert.equal(previewAutoUpdateDisabledReason(stable), null)
assert.match(previewAutoUpdateDisabledReason(preview)!, /do not use the stable update feed/)
assert.throws(() => createDesktopBuildMetadata({ ZYRA_BUILD_DISTRIBUTION: 'preview' }), /require/)
assert.throws(() => createDesktopBuildMetadata({ ZYRA_BUILD_DISTRIBUTION: 'preivew' }), /Unknown/)
assert.throws(() => createDesktopBuildMetadata({ ZYRA_BUILD_SOURCE_SHA: 'main' }), /full commit/)
assert.throws(() => createDesktopBuildMetadata({ ZYRA_BUILD_SOURCE_REPOSITORY: '../source' }), /Invalid/)
const root = new URL('../', import.meta.url)
const main = readFileSync(new URL('src/main/index.ts', root), 'utf8')
assert.match(main, /if \(!identity\.isolated\) return/)
assert.match(main, /if \(!isPreviewDistribution\(\)\)\s*\{\s*void registerInstalledDesktop/)
const terminal = readFileSync(new URL('src/main/terminal-command-service.ts', root), 'utf8')
assert.equal(terminal.match(/if \(!canManageGlobalTerminalCommand\(app\.isPackaged\)\)/g)?.length, 2)
const updater = readFileSync(new URL('src/main/update/manager.ts', root), 'utf8')
assert.match(updater, /return previewAutoUpdateDisabledReason\(\) \|\| getAutoUpdateDisabledReason/)
const installer = readFileSync(new URL('build/preview-installer.nsh', root), 'utf8')
assert.doesNotMatch(installer, /WriteReg|FileWrite|DeleteReg|ZyraInstallFileIcons/)
console.log('Preview identity: stable/dev preservation, isolated profile/namespace, source validation, launcher and updater guards passed')
