import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { addProjectDraftFolder, projectCreationCandidate, projectCreationInput, projectFolderKey } from '../src/renderer/src/lib/projects/project-creation-draft'

assert.deepEqual(projectCreationInput('  Example   Project ', []), { name: 'Example Project', folders: [] })
assert.throws(() => projectCreationInput('   ', []), /project name/)
assert.throws(() => projectCreationInput('x'.repeat(121), []), /120/)
const paths = addProjectDraftFolder(addProjectDraftFolder([], ' C:/Projects/app '), 'C:/Projects/docs')
assert.deepEqual(projectCreationInput('App', paths), { name: 'App', folders: [{ path: 'C:/Projects/app', access: 'read-write' }, { path: 'C:/Projects/docs', access: 'read-write' }] })
assert.throws(() => addProjectDraftFolder(paths, 'c:\\PROJECTS\\APP\\'), /already included/)
assert.throws(() => addProjectDraftFolder([], ' '), /folder path/)
assert.throws(() => addProjectDraftFolder(Array.from({ length: 32 }, (_, i) => `/fixture/${i}`), '/fixture/another'), /32/)
assert.notEqual(projectFolderKey('/work/Project'), projectFolderKey('/work/project'))
assert.equal(projectFolderKey('C:\\Projects\\App\\'), 'c:/projects/app')
assert.equal(projectCreationCandidate({ candidateId: 'candidate', candidatePath: 'C:/Projects/App' }, ['c:/projects/app']), 'candidate')
assert.equal(projectCreationCandidate({ candidateId: 'candidate', candidatePath: 'C:/Projects/App' }, []), undefined)

const source = (file: string) => readFileSync(resolve(import.meta.dir, '../src', file), 'utf8')
const rail = source('renderer/src/pages/assistant/AssistantConnectedSessionsRail.tsx')
assert.match(rail, /await requestProjectCreation\(\)/)
assert.doesNotMatch(rail, /createProjectSessionResult\(/, 'New Project cannot bypass the reviewed setup through the legacy folder-only path')
assert.match(rail, /if \(!project\) return[\s\S]*createAssistantChatAndNavigate/)
assert.match(source('renderer/src/App.tsx'), /<ProjectCreationProvider>[\s\S]*<AppContent/)
const settings = source('renderer/src/pages/settings/ProjectsSettings.tsx')
assert.match(settings, /await requestProjectCreation\(\)/)
assert.doesNotMatch(settings, /createEmptyProject|newProjectName/)
const conversation = source('renderer/src/pages/assistant/AssistantConversationPane.tsx')
assert.match(conversation, /chooseProjectFolder\(requestProjectCreation\)/)
assert.match(settings, /candidateId: candidate.id, candidatePath: candidate.path/, 'detected-folder review remains available in Settings')
assert.match(conversation, /onCreateProject=\{composerIsCentered \? handleCreateNewChatProject : undefined\}/)
assert.doesNotMatch(conversation, /detectedProjectChoices|handleImportDetectedProject/)
assert.doesNotMatch(conversation, /actions\.(?:chooseProjectPath|createProjectSession)\(/)
const dialog = source('renderer/src/components/projects/ProjectCreationDialog.tsx')
assert.match(dialog, /showModal\(\)/)
assert.match(dialog, /nameRef.current\?\.focus\(\)/)
assert.match(dialog, /data-zyra-native-view-occluder="true"/)
assert.match(dialog, /if \(!busy\) onClose\(\)/)
assert.match(dialog, /role="alert"/)
assert.doesNotMatch(dialog, /project-creation-hint|project-creation-empty|line-clamp|truncate/)
assert.doesNotMatch(source('renderer/src/components/projects/project-creation.css'), /border-(?:top|bottom|block):/, 'Project setup uses spacing rather than section dividers')
const form = source('renderer/src/lib/projects/useProjectCreationForm.ts')
assert.match(form, /if \(operation.current\) return/)
assert.match(form, /if \(folderDraft.trim\(\)\)/)
assert.match(form, /createProject\(input, projectCreationCandidate/)
assert.equal((form.match(/assistant\.createProject\(/g) || []).length, 1)
assert.match(source('renderer/src/pages/assistant/useAssistantProjectCatalog.ts'), /revision === requestRevision.current/)
assert.match(source('renderer/src/lib/projects/project-creation.tsx'), /if \(project\) notifyProjectCatalogChanged\(\)/)
console.log('Project setup draft validation, canonical folder deduplication, cancellation wiring, creation entry points, catalog refresh and dialog contracts: ok')
