import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { renderToStaticMarkup } from 'react-dom/server'
const read = (path: string) => readFileSync(new URL(`../src/renderer/src/${path}`, import.meta.url), 'utf8')
const css = read('index.css')
assert.match(css, /details::details-content/, 'native Settings disclosures have a shared animation')
assert.match(css, /interpolate-size: allow-keywords/)
assert.match(css, /content-visibility 220ms allow-discrete/)
assert.match(css, /prefers-reduced-motion: reduce[\s\S]*details::details-content/)
assert.match(css, /zyra-reduce-motion[\s\S]*details::details-content/)
assert.match(css, /@keyframes provider-add-page-in-right/, 'provider drill-in uses real keyframes, not a dead utility')
assert.match(css, /@keyframes provider-add-page-in-left/)
assert.match(css, /prefers-reduced-motion: reduce[\s\S]*?\.animate-provider-add-in-right/, 'provider drill-in respects reduced motion')
const shell = read('pages/settings/SettingsShell.tsx')
assert.match(shell, /data-settings-search-opening/, 'exact search reveal preserves immediate target layout')
const { SettingsExpander } = await import('../src/renderer/src/pages/settings/SettingsExpander')
const closed = renderToStaticMarkup(<SettingsExpander open={false}><button>Advanced action</button></SettingsExpander>)
assert.match(closed, /aria-hidden="true"/); assert.match(closed, /inert=""/); assert.doesNotMatch(closed, /Advanced action/)
assert.match(renderToStaticMarkup(<SettingsExpander open><button>Advanced action</button></SettingsExpander>), /Advanced action/)
const { availableProviderAddChoices } = await import('../src/renderer/src/pages/settings/providers/provider-add-options')
assert.deepEqual(availableProviderAddChoices([], false, false).map(option => option.id), ['openai-codex', 'openai', 'opencode', 'opencode-harness', 'anthropic', 'custom'])
assert.deepEqual(availableProviderAddChoices(['opencode', 'custom-example'], true, false).map(option => option.id), ['openai-codex', 'openai', 'opencode-harness', 'anthropic', 'custom'])
assert.deepEqual(availableProviderAddChoices(['opencode', 'opencode-harness', 'anthropic'], true, true).map(option => option.id), ['openai-codex', 'custom'], 'another ChatGPT account and custom endpoint stay available')
assert.deepEqual(availableProviderAddChoices(['opencode-harness'], false, false).map(option => option.id), ['openai-codex', 'openai', 'opencode', 'anthropic', 'custom'], 'a connected harness is not offered again')
const { groupProviderAddChoices } = await import('../src/renderer/src/pages/settings/providers/provider-add-options')
const topRows = groupProviderAddChoices(availableProviderAddChoices([], false, false))
assert.deepEqual(topRows.map(row => row.kind === 'group' ? `group:${row.group.id}` : `leaf:${row.choice.id}`), ['group:openai', 'group:opencode', 'leaf:anthropic', 'leaf:custom'])
assert.deepEqual(groupProviderAddChoices(availableProviderAddChoices(['opencode', 'custom-example'], true, false).filter(choice => choice.id !== 'opencode-harness')).map(row => row.kind === 'group' ? `group:${row.group.id}` : `leaf:${row.choice.id}`), ['group:openai', 'leaf:anthropic', 'leaf:custom'], 'OpenAI still offers another subscription account when one is connected')
const { ProviderAddPicker } = await import('../src/renderer/src/pages/settings/providers/ProviderAddPicker')
const choices = availableProviderAddChoices([], false, false)
const picker = renderToStaticMarkup(<ProviderAddPicker choices={choices} onSelect={() => {}} />)
assert.doesNotMatch(picker, /ChatGPT subscription<\/span>/, 'leaf options wait one level down')
assert.doesNotMatch(picker, /OpenCode harness<\/span>/)
assert.match(picker, /animate-provider-add-in-right/, 'the picker transition runs on mount')
assert.match(picker, /OpenAI<\/span>/, 'vendors fold into a top-level group row')
assert.match(picker, /OpenCode<\/span>/)
assert.match(picker, /viewBox="0 0 32 40"/, 'the OpenCode vendor row shows the real mark, not a plug')
assert.match(picker, /grid h-8 w-8 shrink-0 place-items-center/, 'every provider icon aligns without a boxed chip')
assert.doesNotMatch(picker, /bg-\[var\(--settings-control\)\]/, 'provider icons do not sit in boxed chips')
assert.doesNotMatch(picker, />2<\//, 'vendor rows avoid a redundant option-count badge')
assert.match(picker, /Claude API/)
assert.match(picker, /Custom endpoint/)
const openAiPage = renderToStaticMarkup(<ProviderAddPicker choices={choices} onSelect={() => {}} initialGroupId="openai" />)
assert.match(openAiPage, /ChatGPT subscription/)
assert.match(openAiPage, /OpenAI API/)
assert.match(openAiPage, /Back to providers/)
const openCodePage = renderToStaticMarkup(<ProviderAddPicker choices={choices} onSelect={() => {}} initialGroupId="opencode" />)
assert.match(openCodePage, /OpenCode Zen/)
assert.match(openCodePage, /OpenCode harness/)
assert.match(openCodePage, /No API key/)
const { OpenAIConnectionRows } = await import('../src/renderer/src/pages/settings/providers/OpenAIConnectionRows')
const noop = () => {}
const connection = {
    desktopHost: true, connectionError: null, connectionAction: null, connectionBusy: false,
    chatGptConnection: { configured: true, verified: true }, apiKeyConnection: { configured: false, verified: false },
    activeDefaultMethod: 'chatgpt', apiKeyDialogOpen: false, apiKeyDraft: '', disconnectMethod: null,
    setApiKeyDialogOpen: noop, setApiKeyDraft: noop, setDisconnectMethod: noop, refreshAll: noop, connectChatGpt: noop, connectApiKey: noop, switchDefaultConnection: noop, disconnect: noop
} as unknown as Parameters<typeof OpenAIConnectionRows>[0]['connection']
const visibleRows = renderToStaticMarkup(<OpenAIConnectionRows connection={connection} />)
assert.match(visibleRows, /ChatGPT subscription/)
assert.doesNotMatch(visibleRows, /OpenAI API key|Add key|Not connected/)
const waitingRows = renderToStaticMarkup(<OpenAIConnectionRows connection={{ ...connection, connectionAction: 'chatgpt' }} />)
assert.match(waitingRows, /Cancel sign-in/, 'the pending reconnect keeps a visible cancel action')
const needsAttention = renderToStaticMarkup(<OpenAIConnectionRows connection={{ ...connection, chatGptConnection: { ...connection.chatGptConnection!, verified: false } }} />)
assert.match(needsAttention, /Needs attention/, 'saved connections remain recoverable after a failed health check')
const rows = read('pages/settings/providers/OpenAIConnectionRows.tsx')
assert.match(rows, /chatGptConnection\?\.configured \? \(/)
assert.match(rows, /apiKeyConnection\?\.configured \? \(/)
assert.match(rows, /<SettingsDialog\s+open=\{apiKeyDialogOpen\}/, 'the key dialog survives while its absent row is hidden')
const providers = read('pages/settings/ModelProviderConnections.tsx')
assert.match(providers, /data-add-provider-row="true"/)
assert.match(providers, /<ProviderAddPicker/)
assert.match(providers, /initialProvider=\{addProvider\}/)
assert.match(providers, /<HarnessConnectPanel/, 'the harness connects through its own explicit opt-in panel, never the key form')
assert.match(providers, /addProvider === 'opencode-harness'/)
assert.match(providers, /description=""/, 'connection rows no longer leak raw model addresses')
const providerPage = read('pages/settings/providers/ProviderConnections.tsx')
assert.doesNotMatch(providerPage, /New-chat default/, 'the redundant default row is gone')
const panel = read('pages/settings/providers/HarnessConnectPanel.tsx')
assert.match(panel, /detectHarness/, 'detection runs on mount and never connects')
assert.match(panel, /connectHarness/, 'connecting requires the explicit confirm action')
assert.match(panel, /opencode auth login/)
const owner = read('pages/settings/providers/ProviderConnections.tsx')
assert.match(owner, /await connection\.connectChatGpt\(method\)/)
assert.match(owner, /connection\.setApiKeyDialogOpen\(true\)/)
console.log('Settings disclosure/provider flow: native motion, reduced motion, safe closed state, missing-provider choices and existing auth wiring: ok')
